### ISSUE TITLE
Exception: Could not calculate correct fixture method on boolean data types

### ISSUE THREAD

**Issue by dolbex** [JeffreyWay/Laravel-Test-Helpers#2]
Hey Jeffrey - Seems there might be a data type missing from the DataStore.php for tinyint/boolean data types. Otherwise those controllers fail completely.

**Comment by JeffreyWay** [comment]
Fixed. ba623e2485e133ee650e5f84c6adf36d84ca61f3

**Comment by dolbex** [comment]
Hey, not sure where really to put this but I wanted to just shout out and say thanks for the great work you're doing at Envato. I come from the CakePHP world and you really made the leap to Laravel just about as easy as possible. If you ever head 2 hours south to Atlanta hit me up and we'll buy you a beer! :)

**Comment by JeffreyWay** [comment]
Thanks!!
