### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by claar** [JeffreyWay/Laravel-Test-Helpers#32]
Can you please specify a license for this package? Thanks!

**Comment by JeffreyWay** [comment]
I'll add it. But, it's "do whatever you want." Applies to all of my packages.

**Comment by GrahamCampbell** [comment]
Have you considered DBAD by philsturgeon? It's a laugh.

**Comment by ChipWolf** [comment]
I would also recommend the WTFPL – Do What the Fuck You Want to Public License http://www.wtfpl.net/

**Comment by artob** [comment]
@JeffreyWay, in case your intent is to release the code wholly unencumbered, free for anyone to use for any purpose and absent any licensing headaches, you could use either of the [CC0](http://creativecommons.org/publicdomain/zero/1.0/) or the [Unlicense](http://unlicense.org/) public domain dedications. Plenty of examples to be [found](https://github.com/search?o=desc&q=%22public+domain%22&ref=searchresults&s=indexed&type=Code) right here on GitHub.
